# Build changes before merging the PR
name: ci

on:
  pull_request:
    branches: [ main ]
  
  push:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
    build:
      runs-on: ubuntu-latest
      steps:

        - uses: actions/checkout@v3.6.0
        - uses: actions/setup-node@v3
          with:
            node-version: '18'
            cache: 'npm'

        - name: Build project 🔧
          run: | 
            npm install
            npm run build

        - name: Run tests
          run: | 
            npm t
